<h2><?= $data->title ?></h2>

<h3>Netzwaerk Links</h3>
<?= sprintf('<p><a href="%1$s"><strong>%2$s</strong> %3$s</a></p>', $data->urlKnow, __('Know', 'nxtheme'), __('for Nx WordPress Kickstart', 'nxtheme')) ?>
<?= sprintf('<p><a href="%1$s"><strong>%2$s</strong> %3$s</a></p>', $data->urlJira, __('Jira', 'nxtheme'), __('for Nx WordPress Kickstart', 'nxtheme')) ?>


<hr />

<h2>Heading H2</h2>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>
	<ul>
		<li>List Item</li>
		<li>List Item</li>
		<li>List Item</li>
	</ul>

<h3>Heading H3</h3>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<blockquote>
	This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote.
</blockquote>

<h4>Heading H4</h4>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<ul>
	<li>My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. </li>
	<li>My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. </li>
</ul>

<a href="" class="button">Button</a>

<form>
	<p>
		<label for="example-input">Input Field Label:</label><input id="example-input" type="text" value="" placeholder="Placeholder">
	</p>
	<p>
		<label for="example-select">Select Field Label:</label>
		<select id="example-select" >
			<option value="Option 1">Option 1</option>
			<option value="Option 2">Option 2</option>
			<option value="Option 3">Option 3</option>
		</select>
	</p>
	<p>
		<label for="example-textarea">Textarea Label:</label>
		<textarea name="nachricht" cols="40" rows="4"></textarea></span></p>
	<p>
	<p>
		<input value="Submit"  type="submit">
	</p>
</form>
