<div class="g-row g-layout-teaserlistfooter">
	<div class="g-col previous">
		<? if ($data->paged): ?>
			<a href="<?= get_previous_posts_page_link() ?>" class="link">
				<span class="icon icon-angle-left"></span>
				<span class="label"><?= __('Previous', 'nxtheme') ?></span>
			</a>
		<? endif; ?>
	</div>
	<div class="g-col next">
		<? if ($data->paged < $data->max_num_pages): ?>
			<a href="<?= get_next_posts_page_link() ?>" class="link">
				<span class="icon icon-angle-right"></span>
				<span class="label"><?= __('Next', 'nxtheme') ?></span>
			</a>
		<? endif; ?>
	</div>
</div>
