<div class="image-wrapper" id="teaser-<?= $data->post_id ?>">
	<a href="<?= $data->permalink ?>" class="teaser-link-link">

		<?php
			if($data->thumbnail_id !== '' && class_exists('Picture')) {
				echo Picture::create( 'style', $data->thumbnail_id, array(
		    	'selector' => '#teaser-'.$data->post_id,
		     	'sizes' => array('sticky_teaser_small', 'sticky_teaser_medium', 'sticky_teaser_large')
		    	));
		    }
		?>

		<div class="overlay">
			<div class="content">
				<span class="date"><?= $data->date ?></span>
				<h1 class="teaser-title"><?= $data->title ?></h1>
			</div>
		</div>
	</a>
</div>