<article>
	<header>
		<a href="<?= $data->permalink ?>" class="teaser-link">
			<? if($data->thumbnail_id !== '' && class_exists('Picture')) {

				$settings = array(
				    'attributes' => array(
				        'picture' => array(
				            'class' => 'teaser-image'
				        ),
				        'sizes' => array('teaser_small', 'teaser_medium', 'teaser_large'),
				    )
				);

				echo Picture::create( 'element', $data->thumbnail_id, $settings );

				}
			?>
			<h2 class="teaser-title box-content"><?= $data->title ?></h2>
		</a>
		<div class="meta box-content">
			<span class="date"><?= $data->date ?></span>
			<span class="categories"><?= $data->category_link_list ?></span>
		</div>
	</header>
	<div class="content box-content">
		<?= $data->excerpt ?>
	</div>
</article>